### ISSUE TITLE
Incorrect parsing of escape characters in non qouted strings.

### ISSUE THREAD

**Issue by JustKiddingCode** [drone/drone-yaml#51]
I use a .drone.yml that contains:
```
     - >
        git show HEAD | grep 'Apply:' | tr -d '[:blank:]' |
        sed -e 's/^Apply://' | tr ',' '\n' > $hostfile
```
According to the YAML spec[1] the newline character \n should be treated
like the literal backslash + n it is.
In drone '\n' gets translated to a new line. This destroys my tr command.

[1] https://yaml.org/spec/current.html#id2517668

**Comment by bradrydzewski** [comment]
hey there, we use the [github.com/go-yaml/yaml](https://github.com/go-yaml/yaml) parsing library.  Any issues with incorrect parsing would need to be resolved upstream in this library.
