### ISSUE TITLE
An invalid metadata.label value occurred during pipeline execution in k8s due to the name of step

### ISSUE THREAD

**Issue by domgoer** [drone/drone-yaml#53]
The following problems arise with using a drone.

![image](https://user-images.githubusercontent.com/31119455/67082055-ef2e7d80-f1ca-11e9-9082-b392cc99c142.png)

The reason is that `k8s` limits the value of `metadata.Labels` on the resource, and as mentioned in [#12 ](https://github.com/drone/drone-yaml/issues/12), whether this should be rejected in the linter phase.

Given that there are multiple `runtime` in drone, would it be better to execute the respective `linter` before each runtime executes the pipeline?  

It should not be like this, allow errors to occur during execution

**Comment by bradrydzewski** [comment]
Hi there, please note that the native kubernetes runtime was deprecated back in April. See https://github.com/drone/drone-runtime/issues/69

**Comment by domgoer** [comment]
Thank you for your answer. I'll close this issue.

**Comment by bradrydzewski** [comment]
I recommend watching [drone-runners/drone-runner-kube](https://github.com/drone-runners/drone-runner-kube) which will be the home for our second attempt at a kubernetes runtime. We have already had some high level design discussions and I expect development to begin in a few weeks.
